sudo: required
dist: trusty
group: edge
language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml
